#!/usr/bin/env python3
import argparse
from image_recognition_age_gender.age_gender_estimator import AgeGenderEstimator
import cv2
import os

# Assign description to the help doc
parser = argparse.ArgumentParser(description='Get face properties using PyTorch')

# Add arguments
parser.add_argument('image', type=str, help='Image')
parser.add_argument('--weights-path', type=str, help='Path to the weights of the WideResnet model',
                    default=os.path.expanduser('~/data/pytorch_models/best-epoch47-0.9314.onnx'))
parser.add_argument('--image-size', type=int, help='Size of the input image', default=64)
parser.add_argument('--depth', type=int, help='Depth of the network', default=16)
parser.add_argument('--width', type=int, help='Width of the network', default=8)

args = parser.parse_args()

# Read the image
img = cv2.imread(args.image)

estimator = AgeGenderEstimator(args.weights_path, args.image_size, args.depth, args.width)

print(estimator.estimate([img]))
