#!/usr/bin/env python
from __future__ import print_function
import argparse
from image_recognition_color_extractor import ColorExtractor
import cv2

# Assign description to the help doc
parser = argparse.ArgumentParser(description='Get the primary colors')

# Add arguments
parser.add_argument('image', nargs='+', type=str, help='Image')

args = parser.parse_args()

extractor = ColorExtractor()
print(extractor.extract_colors([cv2.imread(image) for image in args.image]))
