#!/usr/bin/env python
from __future__ import print_function
import os
import urllib

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--model_path', default=os.path.expanduser('~/keras/models'))
args = parser.parse_args()

os.system('mkdir -p {}'.format(args.model_path))
local_path = os.path.join(args.model_path, 'face_properties_weights.28-3.73.hdf5')

if not os.path.exists(local_path):
    http_path = "https://github.com/tue-robotics/image_recognition/releases/download/" \
                "image_recognition_keras_face_properties_weights.28-3.73/" \
                "image_recognition_keras_face_properties_weights.28-3.73.hdf5"
    print("Downloading model to {} ...".format(local_path))
    urllib.urlretrieve(http_path, local_path)
    print("Model downloaded: {}".format(local_path))
else:
    print("Model already downloaded: {}".format(local_path))
