#!/usr/bin/env python

from rqt_gui.main import Main
import sys

plugin = "image_recognition_rqt.annotation.AnnotationPlugin"
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
