#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from argparse import ArgumentParser

from image_recognition_tensorflow.retrain import defaults, main

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('image_dir', help='Image folder')

    parser.add_argument('model_dir', help='Folder where inception is stored')
    parser.add_argument('output_dir', help='Where to save the trained graph')

    parser.add_argument('--steps', type=int, default=defaults.steps)
    parser.add_argument('--batch', type=int, default=defaults.batch, help='How many images to train on at a time')

    parser.add_argument('--architecture', type=str, default="inception_v3", help="Name of architecture")

    # Controls the distortions used during training.
    parser.add_argument('--flip_left_right', type=bool, default=False,
                        help="""Whether to randomly flip half of the training images horizontally.""")
    parser.add_argument('--random_crop', type=int, default=0,
                        help="""A percentage determining how much of a margin to randomly crop off the training 
                        images.""")
    parser.add_argument('--random_scale', type=int, default=0,
                        help="""A percentage determining how much to randomly scale up the size of the training images by.""")
    parser.add_argument('--random_brightness', type=int, default=0,
                        help="""A percentage determining how much to randomly multiply the training image input pixels up or down by.""")

    args = parser.parse_args()

    main(**vars(args))
