#!/usr/bin/env python

# System
import os
import operator
import sys

# ROS
import rospy

# OpenCV
from cv_bridge import CvBridge, CvBridgeError
import cv2

# Tensorflow
import tensorflow as tf
import numpy as np

# TU/e Robotics
from image_recognition_msgs.srv import Recognize
from image_recognition_msgs.msg import Recognition, CategoryProbability
from image_recognition_util import image_writer

from tensorflow_ros.object_recognizer import ObjectRecognizer

class TensorflowObjectRecognition:
    """ Performs object recognition using Tensorflow neural networks """
    def __init__(self, graph_path, labels_path, save_images_folder):
        """ Constructor
        :param graph_path: string with path + filename (incl. extension) indicating the database location
        :param labels_path: string with path + filename (incl. extension) indicating the location of the text file
        with labels etc.
        :param save_images_folder: Where to store images for debugging or data collection
        """

        try:
            self._recognizer = ObjectRecognizer(graph_path, labels_path)
        except Exception as e:
            err_msg = "Could not instantiate ObjectRecognizer(graph_path='{}', labels_path='{}': {})".format(graph_path, labels_path, e)
            rospy.logerr(err_msg)
            sys.exit(err_msg)

        self._bridge = CvBridge()
        self._save_images_folder = save_images_folder

        self._recognize_srv = rospy.Service('recognize', Recognize, self._recognize_srv_callback)

        rospy.loginfo("TensorflowObjectRecognition initialized:")
        rospy.loginfo(" - graph_path=%s", graph_path)
        rospy.loginfo(" - labels_path=%s", labels_path)
        rospy.loginfo(" - save_images_folder=%s", save_images_folder)

        rospy.loginfo(" - Labels: {}".format(self._recognizer.labels))

    def _recognize_srv_callback(self, req):
        """ Callback function for the recognize. It saves the image on a temporary location and sets _do_recognition
        to True. Subsequently, it waits until the image has been processed (i.e., until _do_recognition is False again)
        and then returns the result
        :param req: image_recognition_msgs.srv.RecognizeRequest
        :return: image_recognition_msgs.srv.RecognizeResponse
        """

        # Convert to cv2/numpy image
        try:
            self._bgr_image = self._bridge.imgmsg_to_cv2(req.image, "bgr8")
        except CvBridgeError as e:
            error_msg = "Could not convert to opencv image: %s" % e
            rospy.logerr(error_msg)
            raise Exception(error_msg)

        # Write raw image
        if self._save_images_folder:
            image_writer.write_raw(self._save_images_folder, self._bgr_image)

        # Beef: perform the actual classification
        sorted_result = self._recognizer.classify(self._bgr_image)

        # Put the result in a ROS service reply
        recognition = Recognition()
        recognition.roi.height = self._bgr_image.shape[:2][0]
        recognition.roi.width = self._bgr_image.shape[:2][1]
        recognition.categorical_distribution.unknown_probability = 0.1  # TODO: How do we know this?
        for res in sorted_result:
            category_probabilty = CategoryProbability(label=res[0], probability=res[1])
            recognition.categorical_distribution.probabilities.append(category_probabilty)

        # Do some logging
        if sorted_result:
            best_label = sorted_result[0][0]
            best_prob = sorted_result[0][1]

            rospy.loginfo("Best recognition result: {} with probability: {}".format(best_label, best_prob))

            # Write unverified annotated image
            if self._save_images_folder:
                image_writer.write_annotated(self._save_images_folder, self._bgr_image, best_label, False)

        return {"recognitions": [recognition]}


if __name__ == '__main__':

    # Start ROS node
    rospy.init_node('tensorflow_ros')

    try:
        _graph_path = os.path.expanduser(rospy.get_param("~graph_path"))
        _labels_path = os.path.expanduser(rospy.get_param("~labels_path"))
        save_images = rospy.get_param("~save_images", True)

        save_images_folder = None
        if save_images:
            save_images_folder = os.path.expanduser(rospy.get_param("~save_images_folder", "/tmp/tensorflow_ros"))
    except KeyError as e:
        rospy.logerr("Parameter %s not found" % e)
        sys.exit(1)

    # Create object
    object_recognition = TensorflowObjectRecognition(graph_path=_graph_path,
                                                     labels_path=_labels_path,
                                                     save_images_folder=save_images_folder)

    rospy.spin()