#!/usr/bin/env python

from rqt_gui.main import Main
import sys

plugin = "image_recognition_tensorflow_rqt.train.TrainPlugin"
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
