name: Industrial CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  industrial_ci:
    name: Industrial CI (${{ matrix.env.ROS_DISTRO }}) - ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: noetic
            ROS_REPO: main
            BEFORE_INSTALL_TARGET_DEPENDENCIES: "pip3 install --upgrade pip && hash -r pip3 && pip3 install --upgrade --progress-bar=off 'scipy>=1.5'"
            ADDITIONAL_DEBS: python3-pip
    env:
      CCACHE_DIR: /home/runner/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
      UPSTREAM_WORKSPACE: 'github:tue-robotics/catkin_lint_cmake#master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
            ${{ runner.os }}-ccache-${{ matrix.ROS_DISTRO }}-
            ${{ runner.os }}-ccache-
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
